/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  scrumSidebar: [
    {
      type: "doc",
      id: "scrum/intro",
    },
  ],
  languagesSidebar: [
    {
      type: "doc",
      id: "languages/intro",
    },
  ],
  cloudInfraSidebar: [
    {
      type: "doc",
      id: "cloud-infrastructure/intro",
    },
  ],
  dataOpsSidebar: [],
  devopsSidebar: [
    {
      type: "doc",
      id: "devops/intro",
    },
    // {
    //   type: 'category',
    //   label: 'GitLab',
    //   items: [
    //     'devops/gitlab/gitlab-installation-ubuntu',
    //     'devops/gitlab/gitlab-runner-installation-ubuntu',
    //     'devops/gitlab/gitlab-backup-and-restore',
    //     'devops/gitlab/gitlab-reactjs-ci-cd',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'GitHub',
    //   items: ['devops/github/intro'],
    // }
  ],
  backendSidebar: [],
  frontendSidebar: [],
  idesDevToolsSidebar: [],
};

module.exports = sidebars;
