/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  scrumSidebar: [
    {
      type: "doc",
      id: "scrum/scrum-concepts",
    },
    {
      type: "doc",
      id: "scrum/scrum-team",
    },
    {
      type: "doc",
      id: "scrum/scrum-artifacts",
    },
    {
      type: "doc",
      id: "scrum/scrum-events",
    },
    {
      type: "doc",
      id: "scrum/defination-of-done",
    },
    {
      type: "doc",
      id: "scrum/product-delivery",
    },
  ],
  languagesSidebar: [
    {
      type: "doc",
      id: "languages/intro",
    },
  ],
  cloudInfraSidebar: [
    {
      type: "doc",
      id: "cloud-infrastructure/intro",
    },
  ],
  devopsSidebar: [
    {
      type: "doc",
      id: "devops/intro",
    },
    {
      type: 'category',
      label: 'Git',
      items: [
        'devops/git/tips',
      ]
    },
    {
      type: 'category',
      label: 'CICD',
      items: [
        'devops/cicd/intro',
        {
          type: 'category',
          label: 'GitHub',
          items: ['devops/cicd/github/intro'],
        },
        {
          type: 'category',
          label: 'GitLab',
          items: [
            'devops/cicd/gitlab/gitlab-installation-ubuntu',
            'devops/cicd/gitlab/gitlab-runner-installation-ubuntu',
            'devops/cicd/gitlab/gitlab-backup-and-restore',
            'devops/cicd/gitlab/gitlab-reactjs-ci-cd',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Containerization',
      items: [
        'devops/containerization/intro',
        {
          type: 'category',
          label: 'Docker',
          items: [
            'devops/containerization/docker/docker-installation'
          ]
        },
        {
          type: 'category',
          label: 'Kubernetes',
          items: [
            'devops/containerization/kubernetes/intro'
          ]
        },
      ]
    },
  ],
  dataOpsSidebar: [
    {
      type: "doc",
      id: "dataops/intro",
    },
  ],
  softwareEngineerSidebar: [
    {
      type: "doc",
      id: "software-engineer/intro",
    },
  ],
  idesDevToolsSidebar: [
    {
      type: "doc",
      id: "ides-and-dev-tools/intro",
    },
  ],
};

module.exports = sidebars;
